/**
 * Quest catalog: the main storyline (25 quests, 6 chapters + postgame) and
 * side quests. Availability is derived from prereqs, level and zone flags.
 */

import type { NpcDef, QuestDef } from './types.ts';

const Q = (q: QuestDef): QuestDef => q;

export const QUESTS: readonly QuestDef[] = [
  // ══ Chapter 1 — The Last Ember ══════════════════════════════════════
  Q({
    id: 'm1_embers',
    offerDialogue: 'dlg_m1_embers_offer',
    turnInDialogue: 'dlg_m1_embers_turnin',
    name: 'Sparks of Trouble',
    main: true,
    chapter: 1,
    level: 1,
    summary:
      'Elder Maren asks you to thin the ember-rats gnawing the hearth-roads — the first steps on a longer road.',
    objectives: [{ kind: 'kill', target: 'e_ember_rat', count: 4 }],
    rewards: { xp: 120, gold: 80, items: { q_sealed_letter: 1 } },
    startNpc: 'npc_maren',
    finishNpc: 'npc_maren',
  }),
  Q({
    id: 'm2_letter',
    offerDialogue: 'dlg_m2_letter_offer',
    turnInDialogue: 'dlg_m2_letter_turnin',
    conversationDialogue: 'dlg_m2_letter_talk',
    name: 'The Sealed Letter',
    main: true,
    chapter: 1,
    level: 2,
    prereqQuest: 'm1_embers',
    summary: "Deliver Maren's sealed letter to Blacksmith Bram — the first clue toward the dawn.",
    objectives: [
      { kind: 'collect', target: 'q_sealed_letter', count: 1 },
      { kind: 'storyEvent', target: 'heard_bram_reading', label: 'Hear Bram read the letter' },
    ],
    rewards: { xp: 150, gold: 100, items: { c_potion: 1 } },
    // The canonical delivery flow (#63): Maren starts it, Bram finishes it.
    startNpc: 'npc_maren',
    finishNpc: 'npc_bram',
  }),
  Q({
    id: 'm3_wolves',
    offerDialogue: 'dlg_m3_wolves_offer',
    turnInDialogue: 'dlg_m3_wolves_turnin',
    name: 'Bold Wolves',
    main: true,
    chapter: 1,
    level: 3,
    prereqQuest: 'm2_letter',
    summary: 'The wolf packs still grow bold as the Flame dims — thin them in the Whisperwood.',
    objectives: [{ kind: 'kill', target: 'e_wolf', count: 3 }],
    rewards: { xp: 250, gold: 120 },
    startNpc: 'npc_maren',
    finishNpc: 'npc_maren',
  }),
  Q({
    id: 'm4_floors',
    offerDialogue: 'dlg_m4_floors_offer',
    turnInDialogue: 'dlg_m4_floors_turnin',
    name: "The Hollow's Threshold",
    main: true,
    chapter: 1,
    level: 5,
    prereqQuest: 'm3_wolves',
    summary:
      "Warden Tom marks the broods feeding the Hollow's rot — cut them down at the threshold.",
    objectives: [
      { kind: 'kill', target: 'e_spider', count: 3 },
      { kind: 'kill', target: 'e_sprite', count: 2 },
    ],
    rewards: { xp: 300, gold: 200 },
    startNpc: 'npc_warden_tom',
    finishNpc: 'npc_warden_tom',
  }),
  Q({
    id: 'm5_arms',
    offerDialogue: 'dlg_m5_arms_offer',
    turnInDialogue: 'dlg_m5_arms_turnin',
    name: 'Steel for the Descent',
    main: true,
    chapter: 1,
    level: 6,
    prereqQuest: 'm4_floors',
    summary:
      "Bram wants real steel in your hands before the Hollow's heart — iron enough to work it.",
    objectives: [{ kind: 'collect', target: 'm_iron_chunk', count: 2 }],
    rewards: { xp: 250, gold: 250, items: { c_potion: 2 } },
    startNpc: 'npc_bram',
    finishNpc: 'npc_bram',
  }),
  Q({
    id: 'm3_roots',
    offerDialogue: 'dlg_m3_roots_offer',
    turnInDialogue: 'dlg_m3_roots_turnin',
    startNpc: 'npc_bram',
    finishNpc: 'npc_bram',
    name: 'Root of the Rot',
    main: true,
    chapter: 1,
    level: 7,
    prereqQuest: 'm5_arms',
    summary: "Cleanse the Rootbound Hollow — reclaim the wood's warmth for what comes next.",
    objectives: [{ kind: 'kill', target: 'e_aranya', count: 1 }],
    rewards: { xp: 400, gold: 250, items: { m_iron_chunk: 1 } },
  }),
  Q({
    id: 'm4_blessing',
    offerDialogue: 'dlg_m4_blessing_offer',
    turnInDialogue: 'dlg_m4_blessing_turnin',
    startNpc: 'npc_bram',
    finishNpc: 'npc_bram',
    name: "Whisperwood's Blessing",
    main: true,
    chapter: 1,
    level: 8,
    prereqQuest: 'm3_roots',
    summary: "Gather ember shards — seed-stock of the dawn — for Bram's forge.",
    objectives: [{ kind: 'collect', target: 'm_ember_shard', count: 6 }],
    rewards: {
      xp: 350,
      gold: 200,
      items: { t_1: 1 },
      flags: ['chapter1Done'],
      unlockZone: 'hollowmere',
    },
  }),

  // ══ Chapter 2 — The Drowned Lowland ══════════════════════════════════
  Q({
    id: 'm5_fen',
    offerDialogue: 'dlg_m5_fen_offer',
    turnInDialogue: 'dlg_m5_fen_turnin',
    // Destination quest (#66): Bram sends you east; the Ferryman completes
    // the journey in Hollowmere. The road IS the quest.
    startNpc: 'npc_bram',
    finishNpc: 'npc_ferryman',
    name: 'Into the Fen',
    main: true,
    chapter: 2,
    level: 9,
    prereqQuest: 'm4_blessing',
    summary: 'Travel to Hollowmere — beyond it, word of stolen light.',
    objectives: [{ kind: 'reach', target: 'hollowmere' }],
    rewards: { xp: 300, gold: 150 },
  }),
  Q({
    id: 'm6_toxin',
    offerDialogue: 'dlg_m6_toxin_offer',
    turnInDialogue: 'dlg_m6_toxin_turnin',
    startNpc: 'npc_ferryman',
    finishNpc: 'npc_ferryman',
    name: "The Water's Bane",
    main: true,
    chapter: 2,
    level: 10,
    prereqQuest: 'm5_fen',
    summary: 'Collect toxin samples — proof that the poisoning can be undone.',
    objectives: [{ kind: 'collect', target: 'q_toxin_sample', count: 4 }],
    rewards: { xp: 900, gold: 400, items: { c_antidote: 2 } },
  }),
  Q({
    id: 'm7_tyrant',
    offerDialogue: 'dlg_m7_tyrant_offer',
    turnInDialogue: 'dlg_m7_tyrant_turnin',
    startNpc: 'npc_ferryman',
    finishNpc: 'npc_ferryman',
    name: 'The Bog Tyrant',
    main: true,
    chapter: 2,
    level: 12,
    prereqQuest: 'm6_toxin',
    summary:
      'Descend into the Sunken Shrine and end Bog Tyrant Vosk — and the despair he feeds on.',
    objectives: [{ kind: 'kill', target: 'e_vosk', count: 1 }],
    rewards: { xp: 1400, gold: 700, flags: ['chapter2Done'] },
  }),
  Q({
    id: 'm8_passage',
    offerDialogue: 'dlg_m8_passage_offer',
    turnInDialogue: 'dlg_m8_passage_turnin',
    startNpc: 'npc_ferryman',
    finishNpc: 'npc_ferryman',
    name: "The Curator's Summons",
    main: true,
    chapter: 2,
    level: 13,
    prereqQuest: 'm7_tyrant',
    summary: "Hear the Ferryman's word about the ruins beyond — another piece of tomorrow waits.",
    objectives: [{
      kind: 'storyEvent',
      target: 'heard_ferrymans_word',
      label: "Hear the Ferryman's word",
    }],
    rewards: { xp: 500, gold: 250, unlockZone: 'sunspire' },
  }),

  // ══ Chapter 3 — The City of Gears ════════════════════════════════════
  Q({
    id: 'm9_spire',
    offerDialogue: 'dlg_m9_spire_offer',
    turnInDialogue: 'dlg_m9_spire_turnin',
    // Destination quest (#66): the Ferryman's summons points east; Ombra
    // receives you in Sunspire.
    startNpc: 'npc_ferryman',
    finishNpc: 'npc_curator',
    name: 'City of Gears',
    main: true,
    chapter: 3,
    level: 15,
    prereqQuest: 'm8_passage',
    summary: 'Reach the Sunspire Ruins, where stolen time is hoarded.',
    objectives: [{ kind: 'reach', target: 'sunspire' }],
    rewards: { xp: 400, gold: 200 },
  }),
  Q({
    id: 'm10_cult',
    offerDialogue: 'dlg_m10_cult_offer',
    turnInDialogue: 'dlg_m10_cult_turnin',
    startNpc: 'npc_curator',
    finishNpc: 'npc_curator',
    name: 'The Hoarded Sun',
    main: true,
    chapter: 3,
    level: 16,
    prereqQuest: 'm9_spire',
    summary: "Break the Sun Cult's hold on the ruins — they worship a sun they never share.",
    objectives: [{ kind: 'kill', target: 'e_cultist', count: 8 }],
    rewards: { xp: 1200, gold: 600, items: { c_ether: 2 } },
  }),
  Q({
    id: 'm11_toll',
    offerDialogue: 'dlg_m11_toll_offer',
    turnInDialogue: 'dlg_m11_toll_turnin',
    startNpc: 'npc_curator',
    finishNpc: 'npc_curator',
    name: "The Vault's Toll",
    main: true,
    chapter: 3,
    level: 17,
    prereqQuest: 'm10_cult',
    summary: 'Break the automatons guarding the Vault of Hours and claim its key.',
    objectives: [{ kind: 'kill', target: 'e_automaton', count: 4 }],
    rewards: { xp: 1500, gold: 700, items: { q_sunspire_key: 1 } },
  }),
  Q({
    id: 'm12_chronolich',
    offerDialogue: 'dlg_m12_chronolich_offer',
    turnInDialogue: 'dlg_m12_chronolich_turnin',
    startNpc: 'npc_curator',
    finishNpc: 'npc_curator',
    name: 'The Hour That Stole Itself',
    main: true,
    chapter: 3,
    level: 19,
    prereqQuest: 'm11_toll',
    summary: 'Enter the Vault of Hours and end the Chronolich — give the stolen hours back.',
    objectives: [{ kind: 'kill', target: 'e_chronolich', count: 1 }],
    rewards: { xp: 3600, gold: 1600, flags: ['chapter3Done'], unlockZone: 'frostpeak' },
  }),

  // ══ Chapter 4 — The Frozen Twin ══════════════════════════════════════
  Q({
    id: 'm13_pass',
    offerDialogue: 'dlg_m13_pass_offer',
    turnInDialogue: 'dlg_m13_pass_turnin',
    // Destination quest (#66): Ombra points north; Rho receives you at the
    // pass.
    startNpc: 'npc_curator',
    finishNpc: 'npc_outcast',
    name: 'The Frozen Road',
    main: true,
    chapter: 4,
    level: 22,
    prereqQuest: 'm12_chronolich',
    summary: 'Cross into Frostpeak Pass, where even the cold keeps a promise.',
    objectives: [{ kind: 'reach', target: 'frostpeak' }],
    rewards: { xp: 600, gold: 300 },
  }),
  Q({
    id: 'm14_emblem',
    offerDialogue: 'dlg_m14_emblem_offer',
    turnInDialogue: 'dlg_m14_emblem_turnin',
    startNpc: 'npc_outcast',
    finishNpc: 'npc_outcast',
    name: "Warden's Marks",
    main: true,
    chapter: 4,
    level: 23,
    prereqQuest: 'm13_pass',
    summary: 'Collect Frost Emblems from the wraiths — oaths that still believe in something.',
    objectives: [{ kind: 'collect', target: 'q_frost_emblem', count: 3 }],
    rewards: { xp: 2400, gold: 900, items: { c_greater_potion: 2 } },
  }),
  Q({
    id: 'm15_wyrm',
    offerDialogue: 'dlg_m15_wyrm_offer',
    turnInDialogue: 'dlg_m15_wyrm_turnin',
    startNpc: 'npc_outcast',
    finishNpc: 'npc_outcast',
    name: 'Heart of the Glacier',
    main: true,
    chapter: 4,
    level: 25,
    prereqQuest: 'm14_emblem',
    summary:
      "Face Jormunis and free the Frostfire — the flame's twin, and winter's promise of spring.",
    objectives: [{ kind: 'kill', target: 'e_jormunis', count: 1 }],
    rewards: { xp: 9000, gold: 3200, flags: ['chapter4Done'], unlockZone: 'cinder' },
  }),

  // ══ Chapter 5 — The Starving Flame ══════════════════════════════════
  Q({
    id: 'm16_ashes',
    offerDialogue: 'dlg_m16_ashes_offer',
    turnInDialogue: 'dlg_m16_ashes_turnin',
    // Destination quest (#66): Rho sends you down from the pass; Sorrel
    // receives you in the Wastes.
    startNpc: 'npc_outcast',
    finishNpc: 'npc_ashen',
    name: 'Through the Ash',
    main: true,
    chapter: 5,
    level: 30,
    prereqQuest: 'm15_wyrm',
    summary: 'Cross the Cinder Wastes, where a starving guardian still keeps faith.',
    objectives: [{ kind: 'reach', target: 'cinder' }],
    rewards: { xp: 900, gold: 450 },
  }),
  Q({
    id: 'm17_plea',
    offerDialogue: 'dlg_m17_plea_offer',
    turnInDialogue: 'dlg_m17_plea_turnin',
    startNpc: 'npc_ashen',
    finishNpc: 'npc_ashen',
    name: "Sorrel's Plea",
    main: true,
    chapter: 5,
    level: 31,
    prereqQuest: 'm16_ashes',
    summary: "Hear Ashen Monk Sorrel's plea — the truth behind the hunger.",
    objectives: [{ kind: 'storyEvent', target: 'heard_sorrels_plea', label: "Hear Sorrel's plea" }],
    rewards: { xp: 1500, gold: 700, items: { c_super_potion: 1 } },
  }),
  Q({
    id: 'm18_sigil',
    offerDialogue: 'dlg_m18_sigil_offer',
    turnInDialogue: 'dlg_m18_sigil_turnin',
    startNpc: 'npc_ashen',
    finishNpc: 'npc_ashen',
    name: 'Brand of the Betrayed',
    main: true,
    chapter: 5,
    level: 32,
    prereqQuest: 'm17_plea',
    summary: 'Collect Cinder Sigils — the sorrow of the faithful, honored into a lamp.',
    objectives: [{ kind: 'collect', target: 'q_cinder_sigil', count: 3 }],
    rewards: { xp: 4000, gold: 1500, items: { c_phoenix_feather: 1 } },
  }),
  Q({
    id: 'm19_ignivar',
    offerDialogue: 'dlg_m19_ignivar_offer',
    turnInDialogue: 'dlg_m19_ignivar_turnin',
    startNpc: 'npc_ashen',
    finishNpc: 'npc_ashen',
    name: 'The Last Flame',
    main: true,
    chapter: 5,
    level: 34,
    prereqQuest: 'm18_sigil',
    summary:
      "Descend the Pyre Caldera and face Ignivar — free the flame, don't just end the fight.",
    objectives: [{ kind: 'kill', target: 'e_ignivar', count: 1 }],
    rewards: { xp: 20000, gold: 6500, flags: ['chapter5Done'], unlockZone: 'umbra' },
  }),

  // ══ Chapter 6 — The Dawncaller ══════════════════════════════════
  Q({
    id: 'm20_seam',
    offerDialogue: 'dlg_m20_seam_offer',
    turnInDialogue: 'dlg_m20_seam_turnin',
    // Destination quest (#66): Sorrel sends you up from the Wastes; the
    // Archivist receives you at the Spire.
    startNpc: 'npc_ashen',
    finishNpc: 'npc_archivist',
    name: 'The Space Between',
    main: true,
    chapter: 6,
    level: 38,
    prereqQuest: 'm19_ignivar',
    summary: 'Reach the Umbral Spire, raised by a man who decided tomorrow was over.',
    objectives: [{ kind: 'reach', target: 'umbra' }],
    rewards: { xp: 1500, gold: 700 },
  }),
  Q({
    id: 'm21_loyalty',
    offerDialogue: 'dlg_m21_loyalty_offer',
    turnInDialogue: 'dlg_m21_loyalty_turnin',
    startNpc: 'npc_archivist',
    finishNpc: 'npc_archivist',
    name: 'Give Them Rest',
    main: true,
    chapter: 6,
    level: 39,
    prereqQuest: 'm20_seam',
    summary: 'Cut down the Crownsworn — knights still fighting a war of despair.',
    objectives: [{ kind: 'kill', target: 'e_crownsworn', count: 10 }],
    rewards: { xp: 9000, gold: 3000 },
  }),
  Q({
    id: 'm22_umbral_key',
    offerDialogue: 'dlg_m22_umbral_key_offer',
    turnInDialogue: 'dlg_m22_umbral_key_turnin',
    startNpc: 'npc_archivist',
    finishNpc: 'npc_archivist',
    name: 'The Unlocked Door',
    main: true,
    chapter: 6,
    level: 40,
    prereqQuest: 'm21_loyalty',
    summary: 'Take counsel with the Archivist before climbing to the throne.',
    objectives: [{
      kind: 'storyEvent',
      target: 'heard_archivists_counsel',
      label: "Take the Archivist's counsel",
    }],
    rewards: { xp: 10000, gold: 3500, items: { c_elixir: 1 } },
  }),
  Q({
    id: 'm23_aldric',
    offerDialogue: 'dlg_m23_aldric_offer',
    turnInDialogue: 'dlg_m23_aldric_turnin',
    name: 'The Sundered Crown',
    main: true,
    chapter: 6,
    level: 41,
    prereqQuest: 'm22_umbral_key',
    summary: 'Face King Aldric the Sundered — despair with a crown on it.',
    objectives: [{ kind: 'kill', target: 'e_aldric', count: 1 }],
    rewards: {
      xp: 45000,
      gold: 15000,
      items: { q_sundered_crown: 1 },
      flags: ['chapter6Done'],
      unlockZone: 'abyss',
    },
    // The Archivist is the throne-room send-off and the completion contact:
    // Aldric himself is a boss encounter, not a dialogue NPC (#63).
    startNpc: 'npc_archivist',
    finishNpc: 'npc_archivist',
  }),

  // ══ Postgame — The Abyss ═════════════════════════════════════════════
  Q({
    id: 'm24_below',
    offerDialogue: 'dlg_m24_below_offer',
    turnInDialogue: 'dlg_m24_below_turnin',
    // Destination quest (#66): the Archivist sends you below; Echo of Maren
    // receives you in the Abyss.
    startNpc: 'npc_archivist',
    finishNpc: 'npc_echo',
    name: 'Below Everything',
    main: true,
    chapter: 7,
    level: 45,
    prereqQuest: 'm23_aldric',
    summary: 'Descend into the Abyss — the future needs a witness.',
    objectives: [{ kind: 'reach', target: 'abyss' }],
    rewards: { xp: 20000, gold: 5000 },
  }),
  Q({
    id: 'm25_silence',
    offerDialogue: 'dlg_m25_silence_offer',
    turnInDialogue: 'dlg_m25_silence_turnin',
    startNpc: 'npc_echo',
    finishNpc: 'npc_echo',
    name: 'Before the Dawn',
    main: true,
    chapter: 7,
    level: 45,
    prereqQuest: 'm24_below',
    summary:
      'Face the Warden of the Void at the bottom of the Seam — and come back with the morning.',
    objectives: [{ kind: 'dungeon', target: 'd_seam' }],
    rewards: {
      xp: 90000,
      gold: 30000,
      items: { c_elixir: 2, m_void_fragment: 3 },
      flags: ['seamConquered'],
    },
  }),

  // ══ Side quests ══════════════════════════════════════════════════════
  Q({
    id: 'sq_rats',
    offerDialogue: 'dlg_sq_rats_offer',
    turnInDialogue: 'dlg_sq_rats_turnin',
    name: 'Six Fewer Rats',
    main: false,
    chapter: 1,
    level: 1,
    summary: 'Cull the rats haunting field and wood.',
    objectives: [{ kind: 'kill', target: 'e_rat', count: 6 }],
    rewards: { xp: 90, gold: 60, items: { c_minor_potion: 1 } },
    startNpc: 'npc_lyra',
    finishNpc: 'npc_lyra',
  }),
  Q({
    id: 'sq_ore',
    offerDialogue: 'dlg_sq_ore_offer',
    turnInDialogue: 'dlg_sq_ore_turnin',
    name: 'Ore for the Forge',
    main: false,
    chapter: 1,
    level: 2,
    prereqFlags: ['zone_whisperwood'],
    summary: "Bring Bram iron from the wood's old diggings.",
    objectives: [{ kind: 'collect', target: 'm_iron_chunk', count: 3 }],
    rewards: { xp: 200, gold: 150 },
    startNpc: 'npc_bram',
    finishNpc: 'npc_bram',
  }),
  Q({
    id: 'sq_charm',
    offerDialogue: 'dlg_sq_charm_offer',
    turnInDialogue: 'dlg_sq_charm_turnin',
    name: 'Charms Against Dimming',
    main: false,
    chapter: 1,
    level: 3,
    prereqFlags: ['zone_whisperwood'],
    summary: "Gather ember shards for Lyra's warding charms.",
    objectives: [{ kind: 'collect', target: 'm_ember_shard', count: 4 }],
    rewards: { xp: 220, gold: 120, items: { c_minor_potion: 2 } },
    startNpc: 'npc_lyra',
    finishNpc: 'npc_lyra',
  }),
  Q({
    id: 'sq_locket',
    offerDialogue: 'dlg_sq_locket_offer',
    turnInDialogue: 'dlg_sq_locket_turnin',
    name: 'The Lost Locket',
    main: false,
    chapter: 1,
    level: 4,
    prereqFlags: ['zone_whisperwood'],
    summary: 'Recover a locket from the Woodfang spiders.',
    objectives: [{ kind: 'kill', target: 'e_spider', count: 8 }],
    rewards: { xp: 400, gold: 250, items: { t_1: 1 } },
    // The anonymous ranger is now a real, placed contact (#63).
    startNpc: 'npc_pell',
    finishNpc: 'npc_pell',
  }),
  Q({
    id: 'sq_stag',
    offerDialogue: 'dlg_sq_stag_offer',
    turnInDialogue: 'dlg_sq_stag_turnin',
    startNpc: 'npc_warden_tom',
    finishNpc: 'npc_warden_tom',
    name: 'The Old Guardian',
    main: false,
    chapter: 1,
    level: 5,
    prereqQuest: 'm3_roots',
    summary: 'Put the corrupted stag to rest.',
    objectives: [{ kind: 'kill', target: 'e_stag', count: 1 }],
    rewards: { xp: 500, gold: 300, items: { c_potion: 2 } },
  }),
  Q({
    id: 'sq_boglins',
    offerDialogue: 'dlg_sq_boglins_offer',
    turnInDialogue: 'dlg_sq_boglins_turnin',
    startNpc: 'npc_ferryman',
    finishNpc: 'npc_ferryman',
    name: 'Boglin Cull',
    main: false,
    chapter: 2,
    level: 9,
    prereqFlags: ['zone_hollowmere'],
    summary: 'Reduce the boglin swarms.',
    objectives: [{ kind: 'kill', target: 'e_boglin', count: 10 }],
    rewards: { xp: 800, gold: 350 },
  }),
  Q({
    id: 'sq_hags',
    offerDialogue: 'dlg_sq_hags_offer',
    turnInDialogue: 'dlg_sq_hags_turnin',
    startNpc: 'npc_ferryman',
    finishNpc: 'npc_ferryman',
    name: 'Cackle Season',
    main: false,
    chapter: 2,
    level: 11,
    prereqFlags: ['zone_hollowmere'],
    summary: 'Silence the Fen Hags.',
    objectives: [{ kind: 'kill', target: 'e_fenhag', count: 5 }],
    rewards: { xp: 1100, gold: 450, items: { c_ether: 2 } },
  }),
  Q({
    id: 'sq_scarabs',
    offerDialogue: 'dlg_sq_scarabs_offer',
    turnInDialogue: 'dlg_sq_scarabs_turnin',
    startNpc: 'npc_curator',
    finishNpc: 'npc_curator',
    name: 'Gilded Problem',
    main: false,
    chapter: 3,
    level: 16,
    prereqFlags: ['zone_sunspire'],
    summary: 'Clear the gilded scarab swarms.',
    objectives: [{ kind: 'kill', target: 'e_scarab', count: 12 }],
    rewards: { xp: 1600, gold: 600 },
  }),
  Q({
    id: 'sq_lynx',
    offerDialogue: 'dlg_sq_lynx_offer',
    turnInDialogue: 'dlg_sq_lynx_turnin',
    startNpc: 'npc_curator',
    finishNpc: 'npc_curator',
    name: 'Spire Cats',
    main: false,
    chapter: 3,
    level: 18,
    prereqFlags: ['zone_sunspire'],
    summary: 'Deal with the Spire Lynx pack.',
    objectives: [{ kind: 'kill', target: 'e_spirelynx', count: 6 }],
    rewards: { xp: 2000, gold: 800, items: { t_2: 1 } },
  }),
  Q({
    id: 'sq_wraiths',
    offerDialogue: 'dlg_sq_wraiths_offer',
    turnInDialogue: 'dlg_sq_wraiths_turnin',
    startNpc: 'npc_outcast',
    finishNpc: 'npc_outcast',
    name: 'Laid to Rest',
    main: false,
    chapter: 4,
    level: 23,
    prereqFlags: ['zone_frostpeak'],
    summary: 'Release the Frost Wraiths from their vigil.',
    objectives: [{ kind: 'kill', target: 'e_frostwraith', count: 8 }],
    rewards: { xp: 4000, gold: 1400 },
  }),
  Q({
    id: 'sq_yetis',
    offerDialogue: 'dlg_sq_yetis_offer',
    turnInDialogue: 'dlg_sq_yetis_turnin',
    startNpc: 'npc_outcast',
    finishNpc: 'npc_outcast',
    name: 'Convincing the Yetis',
    main: false,
    chapter: 4,
    level: 25,
    prereqFlags: ['zone_frostpeak'],
    summary: 'Drive the glacier yetis from the pass before they drive you.',
    objectives: [{ kind: 'kill', target: 'e_yeti', count: 4 }],
    rewards: { xp: 5500, gold: 1800, items: { t_3: 1 } },
  }),
  Q({
    id: 'sq_imps',
    offerDialogue: 'dlg_sq_imps_offer',
    turnInDialogue: 'dlg_sq_imps_turnin',
    startNpc: 'npc_ashen',
    finishNpc: 'npc_ashen',
    name: "The Flame's Hiccups",
    main: false,
    chapter: 5,
    level: 31,
    prereqFlags: ['zone_cinder'],
    summary: 'Thin the ember imp flocks.',
    objectives: [{ kind: 'kill', target: 'e_emberimp', count: 14 }],
    rewards: { xp: 8000, gold: 2500 },
  }),
  Q({
    id: 'sq_salamanders',
    offerDialogue: 'dlg_sq_salamanders_offer',
    turnInDialogue: 'dlg_sq_salamanders_turnin',
    startNpc: 'npc_ashen',
    finishNpc: 'npc_ashen',
    name: 'Breaking the Herds',
    main: false,
    chapter: 5,
    level: 33,
    prereqFlags: ['zone_cinder'],
    summary: 'Break the salamander packs that herd travelers into lava.',
    objectives: [{ kind: 'kill', target: 'e_salamander', count: 8 }],
    rewards: { xp: 11000, gold: 3200, items: { t_4: 1 } },
  }),
  Q({
    id: 'sq_shades',
    offerDialogue: 'dlg_sq_shades_offer',
    turnInDialogue: 'dlg_sq_shades_turnin',
    startNpc: 'npc_archivist',
    finishNpc: 'npc_archivist',
    name: 'Naming the Nameless',
    main: false,
    chapter: 6,
    level: 39,
    prereqFlags: ['zone_umbra'],
    summary: 'Dissolve the Umbral Shades.',
    objectives: [{ kind: 'kill', target: 'e_shade', count: 15 }],
    rewards: { xp: 18000, gold: 5000 },
  }),
  Q({
    id: 'sq_echoes',
    offerDialogue: 'dlg_sq_echoes_offer',
    turnInDialogue: 'dlg_sq_echoes_turnin',
    startNpc: 'npc_echo',
    finishNpc: 'npc_echo',
    name: 'Heroes, Honored',
    main: false,
    chapter: 7,
    level: 45,
    prereqFlags: ['zone_abyss'],
    summary: 'Lay the Echoes of Heroes to rest.',
    objectives: [{ kind: 'kill', target: 'e_echo', count: 10 }],
    rewards: { xp: 60000, gold: 15000, items: { t_7: 1 } },
  }),
  Q({
    id: 'sq_null',
    offerDialogue: 'dlg_sq_null_offer',
    turnInDialogue: 'dlg_sq_null_turnin',
    startNpc: 'npc_echo',
    finishNpc: 'npc_echo',
    name: 'Quiet the Hounds',
    main: false,
    chapter: 7,
    level: 45,
    prereqFlags: ['zone_abyss'],
    summary: 'Hunt the Null Hounds.',
    objectives: [{ kind: 'kill', target: 'e_nullhound', count: 15 }],
    rewards: { xp: 70000, gold: 18000, items: { c_elixir: 2 } },
  }),
];

const QUEST_INDEX = new Map(QUESTS.map((q) => [q.id, q]));

export function quest(id: string): QuestDef | undefined {
  return QUEST_INDEX.get(id);
}

export function npc(id: string): NpcDef | undefined {
  return NPC_INDEX.get(id);
}

import { ZONES } from './zones.ts';
import type { ZoneDef } from './types.ts';
const NPC_INDEX = new Map<string, NpcDef>(
  ZONES.flatMap((z) => z.npcs.map((n) => [n.id, n] as const)),
);

// ── Quest contact resolution (#63) ──────────────────────────────────────
// Starter and finisher are independent, explicit contacts. Nothing here
// infers the finisher from a talk objective, and no quest-log-only fallback
// exists: every contact must resolve to a real NPC placed in a zone.

/** The zone where an NPC physically stands — resolution is unambiguous:
 * each NPC id is placed in exactly one zone (content-integrity tested). */
export function zoneOfNpc(npcId: string): ZoneDef | undefined {
  return ZONES.find((z) => z.npcs.some((n) => n.id === npcId));
}

export interface QuestContact {
  npc: NpcDef;
  zone: ZoneDef;
}

/** Resolve a quest's STARTING contact: the NPC that offers it, and the zone
 * where the player can physically meet them. */
export function questStarter(questId: string): QuestContact | undefined {
  const q = QUEST_INDEX.get(questId);
  if (!q) return undefined;
  const npcDef = NPC_INDEX.get(q.startNpc);
  const zone = zoneOfNpc(q.startNpc);
  return npcDef && zone ? { npc: npcDef, zone } : undefined;
}

/** Resolve a quest's FINISHING contact: the NPC that accepts the turn-in,
 * and the zone where the player can physically meet them. May differ from
 * the starter (delivery flows, e.g. m2_letter: Maren → Bram). */
export function questFinisher(questId: string): QuestContact | undefined {
  const q = QUEST_INDEX.get(questId);
  if (!q) return undefined;
  const npcDef = NPC_INDEX.get(q.finishNpc);
  const zone = zoneOfNpc(q.finishNpc);
  return npcDef && zone ? { npc: npcDef, zone } : undefined;
}

/** Look an NPC up by id WITHIN a specific zone — the physical-presence
 * check for on-site quest actions (#64). */
export function npcInZone(zoneId: string, npcId: string): NpcDef | undefined {
  return ZONES.find((z) => z.id === zoneId)?.npcs.find((n) => n.id === npcId);
}
