/** Skill catalog — 8 skills per class, learned at fixed levels. Authored in
 * ascending learn-level order per class (ties keep authored order); the
 * helper enforces this too (#77), so menus can never leak insertion order.
 */

import type { SkillDef } from './types.ts';
import type { ClassId } from '../engine/types.ts';

const S = (s: SkillDef): SkillDef => s;

export const SKILLS: readonly SkillDef[] = [
  // ── Warrior ─────────────────────────────────────────────────────────
  S({
    id: 'sk_cleave',
    name: 'Cleave',
    classId: 'warrior',
    learnLevel: 1,
    mpCost: 4,
    cooldown: 0,
    power: 1.35,
    type: 'phys',
    desc: 'A heavy diagonal cut. 135% ATK.',
  }),
  S({
    id: 'sk_shield_bash',
    name: 'Shield Bash',
    classId: 'warrior',
    learnLevel: 4,
    mpCost: 8,
    cooldown: 3,
    power: 1.0,
    type: 'phys',
    stunChance: 0.35,
    desc: '100% ATK, 35% chance to stun the enemy for a turn.',
  }),
  S({
    id: 'sk_war_cry',
    name: 'War Cry',
    classId: 'warrior',
    learnLevel: 8,
    mpCost: 10,
    cooldown: 4,
    power: 0,
    type: 'buff',
    potency: 0.35,
    duration: 3,
    desc: '+35% ATK for 3 turns.',
  }),
  S({
    id: 'sk_whirlwind',
    name: 'Whirlwind',
    classId: 'warrior',
    learnLevel: 13,
    mpCost: 14,
    cooldown: 2,
    power: 1.75,
    type: 'phys',
    desc: 'Spinning strike. 175% ATK.',
  }),
  S({
    id: 'sk_iron_wall',
    name: 'Iron Wall',
    classId: 'warrior',
    learnLevel: 16,
    mpCost: 10,
    cooldown: 4,
    power: 0,
    type: 'buff',
    potency: 0.6,
    duration: 3,
    desc: '+60% DEF for 3 turns.',
  }),
  S({
    id: 'sk_executioner',
    name: 'Executioner',
    classId: 'warrior',
    learnLevel: 22,
    mpCost: 20,
    cooldown: 3,
    power: 2.4,
    type: 'phys',
    desc: 'A killing stroke. 240% ATK.',
  }),
  S({
    id: 'sk_adrenaline',
    name: 'Adrenaline Surge',
    classId: 'warrior',
    learnLevel: 28,
    mpCost: 18,
    cooldown: 5,
    power: 0,
    type: 'heal',
    potency: 0.3,
    desc: 'Heal 30% of max HP and gain +20% ATK for 2 turns.',
  }),
  S({
    id: 'sk_titans_fall',
    name: "Titan's Fall",
    classId: 'warrior',
    learnLevel: 36,
    mpCost: 30,
    cooldown: 4,
    power: 3.1,
    type: 'phys',
    desc: 'Bring the sky down. 310% ATK.',
  }),

  // ── Mage ────────────────────────────────────────────────────────────
  S({
    id: 'sk_firebolt',
    name: 'Firebolt',
    classId: 'mage',
    learnLevel: 1,
    mpCost: 5,
    cooldown: 0,
    power: 1.4,
    type: 'mag',
    desc: 'A dart of flame. 140% MAG.',
  }),
  S({
    id: 'sk_frost_lance',
    name: 'Frost Lance',
    classId: 'mage',
    learnLevel: 5,
    mpCost: 10,
    cooldown: 2,
    power: 1.55,
    type: 'mag',
    stunChance: 0.2,
    desc: '155% MAG, 20% chance to freeze the enemy.',
  }),
  S({
    id: 'sk_barrier',
    name: 'Barrier',
    classId: 'mage',
    learnLevel: 9,
    mpCost: 12,
    cooldown: 4,
    power: 0,
    type: 'buff',
    potency: 0.5,
    duration: 3,
    desc: '+50% DEF/RES for 3 turns.',
  }),
  S({
    id: 'sk_arcane_surge',
    name: 'Arcane Surge',
    classId: 'mage',
    learnLevel: 13,
    mpCost: 16,
    cooldown: 2,
    power: 2.1,
    type: 'mag',
    desc: '210% MAG.',
  }),
  S({
    id: 'sk_drain_life',
    name: 'Drain Life',
    classId: 'mage',
    learnLevel: 17,
    mpCost: 18,
    cooldown: 3,
    power: 1.5,
    type: 'mag',
    potency: 0.5,
    desc: '150% MAG and heal half the damage dealt.',
  }),
  S({
    id: 'sk_meteor',
    name: 'Meteor',
    classId: 'mage',
    learnLevel: 24,
    mpCost: 26,
    cooldown: 3,
    power: 3.0,
    type: 'mag',
    desc: '300% MAG. The classic.',
  }),
  S({
    id: 'sk_time_warp',
    name: 'Time Warp',
    classId: 'mage',
    learnLevel: 30,
    mpCost: 22,
    cooldown: 5,
    power: 0,
    type: 'buff',
    potency: 0.4,
    duration: 3,
    desc: '+40% MAG/SPD for 3 turns.',
  }),
  S({
    id: 'sk_cataclysm',
    name: 'Cataclysm',
    classId: 'mage',
    learnLevel: 40,
    mpCost: 40,
    cooldown: 4,
    power: 4.2,
    type: 'mag',
    desc: '420% MAG. For endings.',
  }),

  // ── Rogue ───────────────────────────────────────────────────────────
  S({
    id: 'sk_quick_slash',
    name: 'Quick Slash',
    classId: 'rogue',
    learnLevel: 1,
    mpCost: 3,
    cooldown: 0,
    power: 1.25,
    type: 'phys',
    desc: 'Fast cut. 125% ATK.',
  }),
  S({
    id: 'sk_backstab',
    name: 'Backstab',
    classId: 'rogue',
    learnLevel: 5,
    mpCost: 9,
    cooldown: 2,
    power: 1.8,
    type: 'phys',
    desc: "Where the light doesn't reach. 180% ATK.",
  }),
  S({
    id: 'sk_smoke_step',
    name: 'Smoke Step',
    classId: 'rogue',
    learnLevel: 9,
    mpCost: 8,
    cooldown: 4,
    power: 0,
    type: 'buff',
    potency: 0.45,
    duration: 3,
    desc: '+45% SPD for 3 turns — outpace the foe and slip its blows.',
  }),
  S({
    id: 'sk_twin_strike',
    name: 'Twin Strike',
    classId: 'rogue',
    learnLevel: 13,
    mpCost: 13,
    cooldown: 2,
    power: 2.0,
    type: 'phys',
    desc: 'Two blades, one breath. 200% ATK.',
  }),
  S({
    id: 'sk_venom_cut',
    name: 'Venom Cut',
    classId: 'rogue',
    learnLevel: 17,
    mpCost: 12,
    cooldown: 3,
    power: 1.3,
    type: 'debuff',
    potency: 0.25,
    duration: 3,
    desc: '130% ATK and weaken the enemy by 25% for 3 turns.',
  }),
  S({
    id: 'sk_shadow_dance',
    name: 'Shadow Dance',
    classId: 'rogue',
    learnLevel: 22,
    mpCost: 18,
    cooldown: 3,
    power: 2.6,
    type: 'phys',
    desc: '260% ATK, delivered from three directions.',
  }),
  S({
    id: 'sk_assassinate',
    name: 'Assassinate',
    classId: 'rogue',
    learnLevel: 30,
    mpCost: 24,
    cooldown: 4,
    power: 3.2,
    type: 'phys',
    desc: 'One target. One ending. 320% ATK.',
  }),
  S({
    id: 'sk_death_mark',
    name: 'Death Mark',
    classId: 'rogue',
    learnLevel: 40,
    mpCost: 34,
    cooldown: 4,
    power: 4.0,
    type: 'phys',
    desc: '400% ATK. The last thing they see.',
  }),

  // ── Cleric ──────────────────────────────────────────────────────────
  S({
    id: 'sk_smite',
    name: 'Smite',
    classId: 'cleric',
    learnLevel: 1,
    mpCost: 5,
    cooldown: 0,
    power: 1.3,
    type: 'mag',
    desc: 'Holy light as a weapon. 130% MAG.',
  }),
  S({
    id: 'sk_mend',
    name: 'Mend Wounds',
    classId: 'cleric',
    learnLevel: 1,
    mpCost: 8,
    cooldown: 0,
    power: 1.1,
    type: 'heal',
    desc: 'Heal 220% of MAG + 20 HP.',
  }),
  S({
    id: 'sk_blessing',
    name: 'Blessing',
    classId: 'cleric',
    learnLevel: 8,
    mpCost: 12,
    cooldown: 4,
    power: 0,
    type: 'buff',
    potency: 0.3,
    duration: 3,
    desc: '+30% MAG/DEF for 3 turns.',
  }),
  S({
    id: 'sk_radiant_burst',
    name: 'Radiant Burst',
    classId: 'cleric',
    learnLevel: 11,
    mpCost: 16,
    cooldown: 2,
    power: 1.85,
    type: 'mag',
    desc: '185% MAG.',
  }),
  S({
    id: 'sk_holy_ward',
    name: 'Holy Ward',
    classId: 'cleric',
    learnLevel: 16,
    mpCost: 12,
    cooldown: 4,
    power: 0,
    type: 'buff',
    potency: 0.55,
    duration: 3,
    desc: '+55% RES for 3 turns.',
  }),
  S({
    id: 'sk_divine_mending',
    name: 'Divine Mending',
    classId: 'cleric',
    learnLevel: 20,
    mpCost: 20,
    cooldown: 2,
    power: 1.9,
    type: 'heal',
    desc: 'Heal 380% of MAG + 20 HP.',
  }),
  S({
    id: 'sk_judgment',
    name: 'Judgment',
    classId: 'cleric',
    learnLevel: 26,
    mpCost: 24,
    cooldown: 3,
    power: 2.9,
    type: 'mag',
    stunChance: 0.15,
    desc: '290% MAG, 15% chance to stun.',
  }),
  S({
    id: 'sk_miracle',
    name: 'Miracle',
    classId: 'cleric',
    learnLevel: 36,
    mpCost: 32,
    cooldown: 5,
    power: 2.5,
    type: 'heal',
    potency: 1,
    desc: 'Fully restore HP and lift sapped strength.',
  }),
];

const SKILL_INDEX = new Map(SKILLS.map((s) => [s.id, s]));

export function skill(id: string): SkillDef | undefined {
  return SKILL_INDEX.get(id);
}

export function skillsForClass(classId: ClassId, upToLevel: number): SkillDef[] {
  // Stable ascending learnLevel (#77): menus must reflect PROGRESSION, not
  // catalog insertion order. Sort is stable (ES2019+), so equal-level skills
  // keep their authored order — Smite before Mend Wounds at level 1.
  return SKILLS
    .filter((s) => s.classId === classId && s.learnLevel <= upToLevel)
    .sort((a, b) => a.learnLevel - b.learnLevel);
}

/** Skills that become newly available exactly at `level`. */
export function skillsLearnedAt(classId: ClassId, level: number): SkillDef[] {
  return SKILLS.filter((s) => s.classId === classId && s.learnLevel === level);
}
